chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns =[
    path("message/<int:pid>/", views.Chat_view, name="chat_view"),
    path("message/", views.new_message, name="new")
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns =[
    path('', views.index, name='index'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('seller/<str:username>', views.SellerProfile, name='seller_profile'),
    path('sellers/', views.Seller, name='sellers'),
    path('like/<int:pid>/', views.like_product, name='like_product'),
    path('products/<pid>', views.prod_details, name='product-details'),
    path('products', views.Shops, name='products'),
    path('following', views.following, name='following'),
    path('category-shops/<cid>/', views.category_shop, name='cat-shop'),
    path('dashboard/wallet', views.Wallets, name='wallet'),
    path('deposit/', views.process_payment, name='deposit_funds'),
    path('deposit/', views.process_payment, name='deposit_funds'),
    path('wallet/send/', views.process_send_funds, name='process_send_funds'),
    path('purchase/<pid>', views.Purchase, name='purchase'),
    path('process_purchase/<str:pid>/', views.process_purchase, name='process_purchase'),
    path('notifications/', views.notifications_view, name='notifications'),
    
    #tags
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),
    
    
    #search
    path("search/", views.search_view, name="search"),
    
    #settings
    path("settings/", views.settings_view, name="settings"),

    
    

    
    

    
    
    
    
    
    
    
    

]

items/urls.py
from django.urls import path
from items import views


app_name = 'items'

urlpatterns = [
   path('', views.Productitem, name='sell'),
   path('follow_unfollow/<int:user_id>/', views.follow_unfollow, name='follow_unfollow'),
   path('saved/<int:pid>/', views.save_product, name='saved'),  # Ensure pid is treated as an integer
   
   #edit product
   path('edit-product/<pid>', views.EditProduct, name='edit_prod'),
   
   
   
]

onitsha/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("sell/", include("items.urls")),
    path("chat/", include("chat.urls"))
    
    
    
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Registerview, name="sign-up"),
    path("sign-in/", views.Loginview, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("edit-profile/", views.profile_edit, name="edit-profile"),
    path("profile/<int:pid>/", views.profile_view, name="profile"), 
    
    

]

core/forms.py
from django import forms
from core.models import Comments
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm as BasePasswordChangeForm

class CommentForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': "Write review", 
            'class': 'form-control mb-3',
            'id': 'reviewer-text',
            'style': 'width: 100%; max-width: 300px;',
            'rows': 3,
        }))

    class Meta:
        model = Comments
        fields = ['review']

class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(
        label=_("Old Password"),
        widget=forms.PasswordInput(attrs={'class': 'input-field', 'placeholder': "Old password"})
    )
    new_password1 = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput(attrs={'class': 'input-field', 'placeholder': "New password"})
    )
    new_password2 = forms.CharField(
        label=_("Confirm New Password"),
        widget=forms.PasswordInput(attrs={'class': 'input-field', 'placeholder': "Confirm Password"})
    )

    def __init__(self, *args, user=None, **kwargs):
        self.user = user  # Store user instance
        super().__init__(*args, **kwargs)  # Call the superclass's __init__

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.user.check_password(old_password):
            raise forms.ValidationError(_("The old password you entered is incorrect."))
        return old_password

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")
        
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError(_("The new passwords do not match."))
        
        return cleaned_data

    def save(self):
        self.user.set_password(self.cleaned_data["new_password1"])
        self.user.save()  # Save the user instance
        return self.user

class DeactivateAccountForm(forms.Form):
    password = forms.CharField(label=_("Enter your password"), 
    widget=forms.PasswordInput(attrs={'class': 'input-field', 'placeholder': "Deactivate account"}))

core/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from userauths.models import Profile
from django.template.loader import render_to_string
from core.models import Product, Follow, Likes, Comments, Category, Stream, Wallet, WalletTransaction, Notification
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()
from core.forms import CommentForm, PasswordChangeForm, DeactivateAccountForm
from django.db.models import Q
from django.db.models import Min, Max
from django.db.models import Count, Sum, F, Q
from django.db.models import ExpressionWrapper, IntegerField
from django.utils import timezone
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from django.contrib.auth import update_session_auth_hash



# Create your views here.

def index(request):
    user = request.user
    
    # Get all published products, ordered by id
    product = Product.objects.filter(product_status="published").order_by("-id")
    
    # Get liked products if user is authenticated
    liked_products = Likes.objects.filter(user=user).values_list('prod_id', flat=True) if user.is_authenticated else []
    
    # Exclude the logged-in user from the profiles, if authenticated
    profiles = Profile.objects.all()
    if user.is_authenticated:
        profiles = profiles.exclude(user=user)
        # Get list of users the current user is following
        user_following = Follow.objects.filter(follower=user).values_list('following_id', flat=True)
    else:
        user_following = []

    # Add follow status to each profile
    for profile in profiles:
        profile.is_following = profile.user.id in user_following

    # Trending products based on a combination of likes and views
    trending_products = Product.objects.filter(product_status="published").annotate(
        trending_score=F('likes') + F('views')  # Combine likes and views for trending score
    ).order_by('-trending_score')[:5]  # Get top 5 trending products

    # Top sellers based on total product views
    top_sellers = Profile.objects.annotate(
    total_views=Sum('user__product__views'),
    total_likes=Count('user__product__likes'),
    total_comments=Count('user__comments')
    ).annotate(
    combined_score=F('total_views') + F('total_likes') + F('total_comments')
    ).filter(
    Q(total_views__gt=0) | Q(total_likes__gt=0) | Q(total_comments__gt=0)  # Exclude users with no activity
    ).order_by('-combined_score')[:6]

    context = {
        "product": product,
        "profiles": profiles,
        'liked_products': liked_products,
        "trending_products": trending_products,
        "top_sellers": top_sellers
    }

    return render(request, "core/index.html", context)


#Dashboard for the user

@login_required
def Dashboard(request):
    
    user_profile = Profile.objects.get(user=request.user)
    
     # Get current month and year
    now = timezone.now()
    current_month = now.month
    current_year = now.year
    
    products = Product.objects.filter(user=request.user, updated_at__month=current_month, updated_at__year=current_year)
    saved =user_profile.saved_products.all()
    
    total_views = products.aggregate(Sum('views'))['views__sum'] or 0
    liked_products = Likes.objects.filter(user=request.user).values_list('prod_id', flat=True)
    
    # Get current month and year
    now = timezone.now()
    current_month = now.month
    current_year = now.year
    
    followers_count = Follow.objects.filter(following=user_profile.user).count()
    following_count = Follow.objects.filter(follower=user_profile.user).count()
    followers = Follow.objects.filter(following=user_profile.user)
    
    context = {
        "user_profile":user_profile,
        'followers_count': followers_count,
        'following_count': following_count,
        'followers':followers,
        'products':products,
        'total_views':total_views,
        'liked_products':liked_products,
        'saved':saved
    }
    
    
    return render(request, "core/dashboard.html", context)


#seller profile
def SellerProfile(request, username):
    
    user = request.user
    try:
        seller = User.objects.get(username=username)
    except User.DoesNotExist:
        
        messages.warning(request, "User does not exist")
        return redirect('core:seller_profile', username=request.user.username) 
    
    profile = get_object_or_404(Profile, user=seller)
    
    products = Product.objects.filter(user=seller)
    
    followers_count = Follow.objects.filter(following=seller).count()
    following_count = Follow.objects.filter(follower=seller).count()
    followers = Follow.objects.filter(following=seller)
    
    
    # Check follow status
    user_following = Follow.objects.filter(follower=request.user).values_list('following_id', flat=True) if request.user.is_authenticated else []
    
    # Set follow status for the seller's profile
    profile.is_following = profile.user.id in user_following
    
    context = {
        'profile': profile,
        'products': products,
        'followers_count': followers_count,
        'following_count': following_count,
        'followers':followers
    }
    
    return render(request, "core/seller-profile.html", context)

#seller
def Seller(request):
    user = request.user
    
    profiles = Profile.objects.all()  # Exclude the logged-in user

    user_following = Follow.objects.filter(follower=request.user).values_list('following_id', flat=True) if request.user.is_authenticated else []

    # Add follow status to each profile
    for profile in profiles:
        profile.is_following = profile.user.id in user_following
    
    context= {
        "profiles":profiles
    }

    return render(request, "core/sellers.html", context)

#liked product
def like_product(request, pid):
    product = get_object_or_404(Product, id=pid)
    user = request.user

    # Check if the user already liked the product
    existing_like = Likes.objects.filter(user=user, prod=product).first()
    
    if existing_like:
        # If the user has already liked the product, remove the like
        existing_like.delete()
        liked = False
    else:
        # Otherwise, add a new like
        Likes.objects.create(user=user, prod=product)
        liked = True
        
        # Update like count for the product
    like_count = Likes.objects.filter(prod=product).count()
    product.likes = like_count
    product.save()
    
    if liked:
        Notification.objects.create(
            user=product.user,  # The owner of the product
            title="Product Liked",  # Notification title
            message=f'{request.user.username} liked your product "{product.title}".'  # Notification message
        )

    return JsonResponse({'liked': liked, 'like_count': like_count})


def prod_details(request, pid):
    product = get_object_or_404(Product, pid=pid)
    profile = Profile.objects.filter(user=product.user).first()

    # Handle likes for authenticated users
    liked_products = []
    liked = False

    if request.user.is_authenticated:
        liked_products = Likes.objects.filter(user=request.user).values_list('prod_id', flat=True)
        liked = Likes.objects.filter(user=request.user, prod=product).exists()
    
    comments = Comments.objects.filter(prod=product).order_by("-date")
    
    # Track if the product has been viewed by the user using session
    viewed_products = request.session.get('viewed_products', [])
    
    if pid not in viewed_products:
        product.views += 1  # Increment the view count
        product.save()  # Save the updated view count
        viewed_products.append(pid)  # Add product ID to the session
        request.session['viewed_products'] = viewed_products
    
    # Handle comments
    comments_form = CommentForm()
    
    if request.method == 'POST' and request.user.is_authenticated:
        comments_form = CommentForm(request.POST)
        if comments_form.is_valid():
            # Save the comment to the database
            comment = comments_form.save(commit=False)
            comment.prod = product
            comment.user = request.user
            comment.save()
            return redirect('core:product-details', pid=product.pid)
    
    # Check if the user is allowed to make a review (only one review per product)
    make_review = True
    if request.user.is_authenticated:
        user_review_count = Comments.objects.filter(user=request.user, prod=product).count()
        if user_review_count > 0:
            make_review = False
    
    p_image = product.p_image.all()

    context = {
        "p": product,
        "profile": profile,
        "p_image": p_image,
        "liked": liked,  # Pass the liked status to the template
        "liked_products": liked_products,
        "comments_form": comments_form,
        "make_review": make_review,
        "comments": comments
    }

    return render(request, 'core/details.html', context)




@login_required
def Shops(request):
    query = request.GET.get('query', '')
    categories = request.GET.getlist('categories')
    max_price = request.GET.get('max_price', None)
    sort_by = request.GET.get('sort', '')

    products = Product.objects.filter(product_status="published")
    profile = Profile.objects.get(user=request.user)
    liked_products = Likes.objects.filter(user=request.user).values_list('prod_id', flat=True)

    # Apply search filter
    if query:
        products = products.filter(Q(title__icontains=query) | Q(description__icontains=query))

    if categories:
        products = products.filter(category__id__in=categories).distinct()

    # Handle max_price: convert it to a number and ensure correct filtering
    try:
        if max_price is not None and max_price.isdigit():

templates/core/category-shop.html
{% extends "include/base.html" %}

{% block content %}
{% load static %}
{% load humanize %}

<style>
  input[type="range"] {
    -webkit-appearance: none;
    margin-right: 15px;
    height: 7px;
    background: rgba(255, 255, 255, 0.6);
    border-radius: 5px;
    background-image: linear-gradient(#3bb77e, #3bb77e);
    background-size: 100% 100%;
    background-repeat: no-repeat;
    width: 100%;
  }

  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #3bb77e;
    cursor: ew-resize;
    box-shadow: 0 0 2px 0 #555;
    transition: background .3s ease-in-out;
  }

  input[type=range]::-webkit-slider-runnable-track {
    -webkit-appearance: none;
    box-shadow: none;
    border: none;
    background: transparent;
  }
</style>

<div class="inner-banner inner-bg6">
  <div class="container">
    <div class="inner-title">
      <h3>Discover All Onitsha Products</h3>
      <ul>
        <li><a href="index.html">Home</a></li>
        <li>Discover</li>
        <li>Products</li>
      </ul>
      <div class="inner-shape">
        <img src="{% static 'assets/images/inner-banner/inner-shape1.png' %}" alt="Images">
        <img src="{% static 'assets/images/inner-banner/inner-shape2.png' %}" alt="Images">
      </div>
    </div>
  </div>
</div>

<div class="discover-area pt-100 pb-70">
  <div class="container">
    <div class="section-title">
      <h2>Discover Assets</h2>
    </div>
    <div class="row pt-45">
      <div class="col-lg-3">
        <div class="side-bar-area pl-20">
          <div class="side-bar-widget">
            <h3 class="title">Filter <a href="{% url 'core:cat-shop' cid=categories.cid %}">Clear All</a></h3>
            <form action="{% url 'core:cat-shop' cid=categories.cid %}" method="GET" class="search-form">
              <input name="query" type="text" class="form-control" value="{{ query }}" placeholder="Search keyword">
              <button type="submit">
                <i class="ri-search-line"></i>
              </button>
            </form>
          </div>

          <div class="side-bar-widget">
            <h3 class="title">Sort By</h3>
            <div class="form-group select-group">
                <form id="sort-form" method="GET" action="{% url 'core:cat-shop' cid=categories.cid %}">
                    <select name="sort" class="form-select form-control" onchange="this.form.submit()">
                        <option value="">Sort By (Default)</option>
                        <option value="top_liked">Most Liked</option>
                        <option value="low_liked">Least Liked</option>
                    </select>
                </form>
            </div>
        </div>
        
        

          <div class="side-bar-widget-categories">
            <h3 class="title">Categories</h3>
            <form id="categories-form" method="GET" action="{% url 'core:cat-shop' cid=categories.cid %}">
              <ul>
               
                  <li>
                    <label>
                      <input class="form-check-input filter-checkbox" type="checkbox" name="categories" value="{{ categories.id }}" onchange="this.form.submit()">
                      &nbsp;&nbsp;{{ categories.title }}
                    </label>
                  </li>
             
              </ul>
            </form>
          </div>

          <div class="side-bar-widget range">
            <h3>Price Range</h3>
            <form id="price-form" method="GET" action="{% url 'core:cat-shop' cid=categories.cid %}">
              <input 
                  type="range" 
                  name="max_price" 
                  class="slider-range" 
                  value="{{ min_max_price.price__max|floatformat:2 }}" 
                  min="{{ min_max_price.price__min }}" 
                  max="{{ min_max_price.price__max }}" 
                  oninput="document.getElementById('slider-range-value2').innerText = this.value; document.getElementById('max_price_input').value = this.value"
              >
          
              <div class="range-inner mb-2">
                  <div class="d-flex justify-content-between">
                      <div class="caption">
                          From: <strong id="slider-range-value1" class="text-brand">{{ min_max_price.price__min|floatformat:2|intcomma }}</strong>
                      </div>
                      <div class="caption">
                          To: <strong id="slider-range-value2" class="text-brand">{{ min_max_price.price__max|floatformat:2|intcomma }}</strong>
                      </div>
                  </div>
          
                  <!-- Hidden input to capture the max price -->
                  <input type="text" class="form-control" name="max_price" id="max_price_input" value="{{ min_max_price.price__max|floatformat:2 }}" />
              </div>
          
              <button class="btn btn-green mt-20 w-100" type="submit">Filter</button>
          </form>
          
          </div>
        </div>
      </div>

      <div class="col-lg-9">
        <div class="row justify-content-center" id="filtered-product">
          {% for p in product %}
            <div class="col-lg-4 col-md-6">
              <div class="featured-item">
                <div class="featured-item-wrapper">
                  <div class="featured-item-content">
                    <form action="{% url 'core:like_product' p.id %}" method="post" class="like-form">
                      {% csrf_token %}
                      <div class="fav-counter {% if p.id in liked_products %}liked{% endif %}" data-product-id="{{ p.id }}">
                        <button type="submit" class="like-button" style="background: none; border: none; cursor: pointer;">
                          <i class="bi bi-heart"></i>
                        </button>
                        <span class="count">{{ p.likes }}</span>
                      </div>
                    </form>

                    <div class="featured-item-image">
                      <a href="{% url 'core:product-details' p.pid %}"><img src="{{ p.image.url }}" width="304" height="340" alt="" loading="lazy"></a>
                    </div>

                    <div class="featured-item-info">
                      <div class="title"><a href="{% url 'core:product-details' p.pid %}">{{ p.title }}</a></div>
                      <div class="item-meta">
                        <span class="avatar box-26">
                          <a href="08-profile-page.html">
                            <img src="{{ p.user.profile.image.url }}" height="52" width="52" alt="" loading="lazy">
                          </a>
                          <span class="verified"><svg class="crumina-icon"><use xlink:href="#check-icon"></use></svg></span>
                        </span>
                        {{ p.user.profile.user }}
                      </div>
                      <div class="featured-bidding-section">
                        <div class="featured-item-pricebox">
                          <div class="price">₦{{ p.price|intcomma }}</div>
                        </div>
                        <form action="{% url 'items:saved' p.id %}" method="POST" class="save-form" data-product-id="{{ p.id }}">
                          {% csrf_token %}
                          <button type="button" class="pd-detail__click-wrap save-button" data-product-id="{{ p.id }}">
                            {% if p in request.user.profile.saved_products.all %}
                              <i class="bi bi-bookmark-fill"></i>
                            {% else %}
                              <i class="bi bi-bookmark"></i>
                            {% endif %}
                          </button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
             <center> <h1 style="color: red;">No products found.</h1> </center>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/core/following.html
{% extends "include/base.html" %}

{% block content %}
{% load static %}
{% load humanize %}

<style>
  input[type="range"] {
    -webkit-appearance: none;
    margin-right: 15px;
    height: 7px;
    background: rgba(255, 255, 255, 0.6);
    border-radius: 5px;
    background-image: linear-gradient(#3bb77e, #3bb77e);
    background-size: 100% 100%;
    background-repeat: no-repeat;
    width: 100%;
  }

  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #3bb77e;
    cursor: ew-resize;
    box-shadow: 0 0 2px 0 #555;
    transition: background .3s ease-in-out;
  }

  input[type=range]::-webkit-slider-runnable-track {
    -webkit-appearance: none;
    box-shadow: none;
    border: none;
    background: transparent;
  }
</style>

<div class="inner-banner inner-bg5">
  <div class="container">
    <div class="inner-title">
      <h3>Discover All Followed Products</h3>
      <ul>
        <li><a href="index.html">Home</a></li>
        <li>Discover</li>
        <li>Products</li>
      </ul>
      <div class="inner-shape">
        <img src="{% static 'assets/images/inner-banner/inner-shape1.png' %}" alt="Images">
        <img src="{% static 'assets/images/inner-banner/inner-shape2.png' %}" alt="Images">
      </div>
    </div>
  </div>
</div>

<div class="discover-area pt-100 pb-70">
  <div class="container">
    <div class="section-title">
      <h2>Discover Assets</h2>
    </div>
    <div class="row pt-45">
      <div class="col-lg-3">
        <div class="side-bar-area pl-20">
          <div class="side-bar-widget">
            <h3 class="title">Filter <a href="{% url 'core:following' %}">Clear All</a></h3>
            <form action="{% url 'core:following' %}" method="GET" class="search-form">
              <input name="query" type="text" class="form-control" value="{{ query }}" placeholder="Search keyword">
              <button type="submit">
                <i class="ri-search-line"></i>
              </button>
            </form>
          </div>

          <div class="side-bar-widget">
            <h3 class="title">Sort By</h3>
            <form id="sort-form" method="GET" action="{% url 'core:following' %}">
                <select name="sort" class="form-select form-control" onchange="this.form.submit()">
                    <option value="">Sort By (Default)</option>
                    <option value="top_liked">Most Liked</option>
                    <option value="low_liked">Least Liked</option>
                </select>
            </form>
        </div>
        

          <div class="side-bar-widget-categories">
            <h3 class="title">Categories</h3>
            <form id="categories-form" method="GET" action="{% url 'core:following' %}">
              <ul>
                {% for c in category %}
                  <li>
                    <label>
                      <input class="form-check-input filter-checkbox" type="checkbox" name="categories" value="{{ c.id }}" onchange="this.form.submit()">
                      &nbsp;&nbsp;{{ c.title }}
                    </label>
                  </li>
                {% endfor %}
              </ul>
            </form>
          </div>

          <div class="side-bar-widget range">
            <h3>Price Range</h3>
            <form id="price-form" method="GET" action="{% url 'core:following' %}">
                <input 
                    type="range" 
                    name="max_price" 
                    class="slider-range" 
                    value="{{ min_max_price.price__max|floatformat:2 }}" 
                    min="{{ min_max_price.price__min }}" 
                    max="{{ min_max_price.price__max }}" 
                    oninput="document.getElementById('slider-range-value2').innerText = this.value; document.getElementById('max_price_input').value = this.value"
                >
        
                <div class="range-inner mb-2">
                    <div class="d-flex justify-content-between">
                        <div class="caption">
                            From: <strong id="slider-range-value1" class="text-brand">{{ min_max_price.price__min|floatformat:2|intcomma }}</strong>
                        </div>
                        <div class="caption">
                            To: <strong id="slider-range-value2" class="text-brand">{{ min_max_price.price__max|floatformat:2|intcomma }}</strong>
                        </div>
                    </div>
        
                    <input type="text" class="form-control" name="max_price" id="max_price_input" value="{{ min_max_price.price__max|floatformat:2 }}" />
                </div>
        
                <button class="btn btn-green mt-20 w-100" type="submit">Filter</button>
            </form>
        </div>
        </div>
      </div>

      <div class="col-lg-9">
        <div class="row justify-content-center" id="filtered-product">
          {% for p in product %}
            <div class="col-lg-4 col-md-6">
              <div class="featured-item">
                <div class="featured-item-wrapper">
                  <div class="featured-item-content">
                    <form action="{% url 'core:like_product' p.id %}" method="post" class="like-form">
                      {% csrf_token %}
                      <div class="fav-counter {% if p.id in liked_products %}liked{% endif %}" data-product-id="{{ p.id }}">
                        <button type="submit" class="like-button" style="background: none; border: none; cursor: pointer;">
                          <i class="bi bi-heart"></i>
                        </button>
                        <span class="count">{{ p.likes }}</span>
                      </div>
                    </form>

                    <div class="featured-item-image">
                      <a href="05-product-page.html"><img src="{{ p.image.url }}" width="304" height="340" alt="" loading="lazy"></a>
                    </div>

                    <div class="featured-item-info">
                      <div class="title"><a href="06-product-page-v2.html">{{ p.title }}</a></div>
                      <div class="item-meta">
                        <span class="avatar box-26">
                          <a href="08-profile-page.html">
                            <img src="{{ p.user.profile.image.url }}" height="52" width="52" alt="" loading="lazy">
                          </a>
                          <span class="verified"><svg class="crumina-icon"><use xlink:href="#check-icon"></use></svg></span>
                        </span>
                        {{ p.user.profile.user }}
                      </div>
                      <div class="featured-bidding-section">
                        <div class="featured-item-pricebox">
                          <div class="price">₦{{ p.price|intcomma }}</div>
                        </div>
                        <form action="{% url 'items:saved' p.id %}" method="POST" class="save-form" data-product-id="{{ p.id }}">
                          {% csrf_token %}
                          <button type="button" class="pd-detail__click-wrap save-button" data-product-id="{{ p.id }}">
                            {% if p in request.user.profile.saved_products.all %}
                              <i class="bi bi-bookmark-fill"></i>
                            {% else %}
                              <i class="bi bi-bookmark"></i>
                            {% endif %}
                          </button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
             <center> <h1 style="color: red;">No products found.</h1> </center>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}