chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns =[
    path("message/<int:pid>/", views.Chat_view, name="chat_view"),
    path("message/", views.new_message, name="new")
]

onitsha/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("sell/", include("items.urls")),
    path("chat/", include("chat.urls"))
    
    
    
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Registerview, name="sign-up"),
    path("sign-in/", views.Loginview, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("edit-profile/", views.profile_edit, name="edit-profile"),
    path("profile/<int:pid>/", views.profile_view, name="profile"), 
    
    

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


# Create your models here.

class User(AbstractUser):
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =['username']
    
    def __str__(self):
        return self.username
    
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", default='default.jpg')
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=30, blank=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    whatsapp = models.URLField(max_length=200, blank=True, null=True)
    instagram = models.URLField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=200) # +234 (456) - 789
    verified = models.BooleanField(default=False)
    saved_products = models.ManyToManyField('core.Product', related_name="saved_by", blank=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

 
post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your Fullname',
            'class': 'form-control'
        }))
    email = forms.EmailField( widget=forms.EmailInput(attrs={
            'placeholder': 'Your Email Address',
            'class': 'form-control'
        }))
    password1 = forms.CharField( widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter Your Password',
            'class': 'form-control'
        }))
    password2 = forms.CharField( widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirm Your Password',
            'class': 'form-control'
        }))
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']
        
class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))
    location = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Enter your location"}))
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={"id": "input-file", "accept": "image/jpeg, image/png, image/jpg", 'style': 'display:none;'})
    )
    
    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone', 'location']

userauths/views.py
from django.shortcuts import render, redirect, get_object_or_404
from userauths.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from userauths.models import User, Profile
from django.contrib.auth.decorators import login_required

# Create your views here.

def Registerview(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Access Denied..")
        
        return redirect('')
    
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, your account was created successfully")
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect("core:index")
    
    else:
        form = UserRegisterForm()
    context ={
        "form":form,
    }
    return render(request, "userauths/sign-up.html", context)

def Loginview(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        
        try:
            user = User.objects.get(email=email)
            user = authenticate(request,email=email, password=password)
            
            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in")
                return redirect("core:index")
            else:
                messages.warning(request, "email or password does not exist")
                return redirect("userauths:sign-in")
        except:
            messages.warning(request, f"User with this{email} does not exist")
            
    if request.user.is_authenticated:
            messages.warning(request, "You are already logged in")
            return redirect("core:index")
    return render(request, "userauths/sign-in.html")


def logoutView(request):
      logout(request)
      messages.success(request, "You have been logged out")
      return redirect("userauths:sign-in")
  
@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "Profile Updated successfully")
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)
        
    context = {
        "form":form,
        "profile":profile
    }
    return render(request, "userauths/edit-profile.html", context)
     
@login_required
def profile_view(request, pid):
    profile = get_object_or_404(Profile, id=pid)
    context = {
        'profile': profile,
    }
    return render(request, 'profile.html', context)
    
    

templates/userauths/edit-profile.html
{% extends "include/base.html" %}

{% block content %}
{% load static %}
<div class="content-wrapper">
    <div class="container pb-0">
        <!-- Profile Detail Area Start-->
        <div class="video-block section-padding">
            <div class="main-item">
                <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-12 px-0">
                        <div class="profile-area-dashboard">
                            <div class="shapes-bg-big"></div>
                            <div class="my-dash-profile">
                                {% if profile.image %}
                                <img src="{{ profile.image.url }}" id="profile-pic" alt="">
                                {% else %}
                                <img src="{% static 'assets/images/user-1.png' %}" id="profile-pic" alt="">
                                {% endif %}
                                <div class="add-dp" id="OpenImgUpload">
                                    {{form.image}}
                                    <label for="input-file" ><i class="bi bi-camera"></i></label>
                                </div>
                            </div>
                            <div class="profile-dashbd-dt">
                                <div class="item-title-dashbd">
                                    <h4>{{ profile.full_name }}</h4>
                                    <p><span><i class="fas fa-map-marker-alt"></i></span> {{ profile.location }}</p>
                                </div>
                                <div class="dashboard-main-dt">
                                    <ul>
                                        <li>
                                            <div class="lisitng-dtl">
                                                <ins>15</ins>
                                                <span>Listings</span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="lisitng-dtl">
                                                <ins>150</ins>
                                                <span>Followers</span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="lisitng-dtl">
                                                <ins>265</ins>
                                                <span>Following</span>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <button class="setting-btn" onclick="window.location.href = 'setting.html';">Setting</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Profile Detail Area End-->
                <!--Nav Tabs Start -->
                <div class="row">
                    <div class="dashbd-detail-tabs">
                        <div class="col-xl-12 col-md-12 col-sm-12 px-0">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Profile</a>
                                </li>
                            </ul>
                            <!--Nav Tabs End -->
                            <!--Tabs Panes Start -->
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
                                  
                                        {% csrf_token %}
                                        <div class="row lr-row">
                                            <div class="col-md-6">
                                                <div class="account-detls">
                                                    <div class="email-input">
                                                        <div class="midemail">
                                                            <img src="{% static 'images/svg/pencil.svg' %}" alt="">
                                                            <h6>Name</h6>
                                                        </div>
                                                        <div class="inputs">
                                                            {{ form.full_name }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="account-detls">
                                                    <div class="email-input">
                                                        <div class="midemail">
                                                            <img src="{% static 'images/svg/pencil.svg' %}" alt="">
                                                            <h6>About</h6>
                                                        </div>
                                                        <div class="inputs">
                                                            {{ form.bio }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="account-detls">
                                                    <div class="email-input">
                                                        <div class="midemail">
                                                            <img src="{% static 'images/svg/location.svg' %}" alt="">
                                                            <h6>Address</h6>
                                                        </div>
                                                        <div class="inputs">
                                                            {{ form.location }}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="account-detls">
                                                    <div class="email-input">
                                                        <div class="midemail">
                                                            <img src="{% static 'images/svg/phone.svg' %}" alt="">
                                                            <h6>Phone Number</h6>
                                                        </div>
                                                        <div class="inputs">
                                                            {{ form.phone }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="account-detls">
                                                    <div class="email-input">
                                                        <div class="midemail">
                                                            <img src="{% static 'images/svg/url.svg' %}" alt="">
                                                            <h6>Website</h6>
                                                        </div>
                                                        <div class="inputs">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <div class="sends pb-0">
                                                    <input type="submit" value="Save Now">
                                                </div>
                                            </div>
                                        </div>

                                </div>
                            </div>
                            <!--Tabs Panes End -->
                        </div>
                    </div>
                </div>
                <!--Tab Links End-->
            </form>
            </div>                       
        </div>
    </div>
</div>

<script>
    let profilePic = document.getElementById("profile-pic");
    let inputFile = document.getElementById("input-file");

    inputFile.onchange = function() {
        profilePic.src = URL.createObjectURL(inputFile.files[0]);
    }
</script>
{% endblock content %}

templates/userauths/sign-in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/fonts/remixicon.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}">
<link rel="stylesheet" href="{% static 'assets/swiper/swiper-bundle.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/theme-dark.css' %}">

<title>Oni - Marketplace</title>
<link rel="icon" type="image/png" href="{% static 'assets/images/onitsha.png' %}">
</head>
<body>
    
    <section class="vh-100">
        <div class="container py-5 h-100">
          <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
              <img src="{% static 'assets/images/onitsha-img.png' %}"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">

              <h3 class="display-4 fs-7">Sign In </h3>

              {% if messages %}
            {% for message in messages %}
                <strong style="color: red;">{{ message }}</strong>
                      {% endfor %}
          {% endif %}
              <form class="mt-5" method="POST">
                {% csrf_token %}
                <!--imput your full name-->
                <div class="row gy-4 align-items-center mb-4">
                <div data-mdb-input-init class="col-12 mb-2">
                  <input type="email" name="email" id="form1Example13" placeholder="Your Email Address" class="form-control" />
                 
                </div>
                <!-- Email input -->
                <div data-mdb-input-init class="col-12 mb-2">
                  <input type="password" name="password" id="form1Example13" placeholder="Your Password" class="form-control" />
                 
                </div>
      
                <div class="d-flex justify-content-around align-items-center">
                  <!-- Checkbox -->
                  <div class="">
                    <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
                    <label class="form-check-label" for="form1Example3">You agree to our terms and condition </label>
                  </div>
                  <a href="#!">Forgot password?</a>
                </div>
      
                <!-- Submit button -->
                <div class="row mb-4 align-items-center">
                  <div class="sign">
                <button type="submit">Sign In</button>
              </div>
                
                      <center> <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p></center>
                
      
                <a data-mdb-ripple-init class="btn btn-primary btn-lg btn-block" style="background-color: #fff; color: #000; border-color: #ccc;" href="{% url 'userauths:sign-up' %}"
                  role="button">
                  <i class="bi bi me-2" style="color: black;"></i>Don't have an account signup
                </a>
                </div
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>>


    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
    
    <script src="{% static 'assets/js/meanmenu.min.js' %}"></script>
    
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    
    <script src="{% static 'assets/js/countdown.min.js' %}"></script>
    
    <script src="{% static 'assets/js/ajaxchimp.min.js' %}"></script>
    
    <script src="{% static 'assets/js/form-validator.min.js' %}"></script>
    
    <script src="{% static 'assets/js/contact-form-script.js' %}"></script>
    <script src="{% static 'assets/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script async src="{% static 'assets/js/svg-loader.js' %}"></script>
</body>
</html>

templates/userauths/sign-up.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/fonts/remixicon.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}">
<link rel="stylesheet" href="{% static 'assets/swiper/swiper-bundle.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/theme-dark.css' %}">

<title>Oni - Marketplace</title>
<link rel="icon" type="image/png" href="{% static 'assets/images/onitsha.png' %}">
</head>
<body>
    
   
        <div class="container py-5 h-100">
          <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
              <img src="{% static 'assets/images/onitsha-img.png' %}"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">

              <h3 class="display-4 fs-7">Sign Up </h3>
              <form method="POST" class="mt-5">
                  {% if form.errors%}
                  <div class="alert alert-danger">
                      <strong>{{form.errors}}</strong>
                  </div>
                  {% endif %}
                <!--imput your full name-->
                {% csrf_token %}
                <div class="row gy-4 align-items-center mb-4">
                <div data-mdb-input-init class="col-12 mb-2">
                    {{ form.username }}
                 
                </div>
                <!-- Email input -->
                <div data-mdb-input-init class="col-12 mb-2">
                    {{ form.email }}
                 
                </div>
      
                <!-- Password input -->
                <div data-mdb-input-init class="col-6 mb-2">
                    {{ form.password1 }}
                </div>

                <div data-mdb-input-init class="col-6 mb-2">
                    {{ form.password2 }}
                </div>
      
                <div class="d-flex justify-content-around align-items-center">
                  <!-- Checkbox -->
                  <div class="">
                    <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
                    <label class="form-check-label" for="form1Example3">You agree to our terms and condition </label>
                  </div>
                  <a href="{% url 'userauths:sign-in' %}">Sign in?</a>
                </div>
      
                <!-- Submit button -->
                <div class="row mb-4 align-items-center">
                  <div class="sign">
                <button type="submit">Sign up</button>
              </div>
                
                
      
              
                </div>
                </div>
              </form>
            </div>
          </div>
        </div>
   


    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
    
    <script src="{% static 'assets/js/meanmenu.min.js' %}"></script>
    
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    
    <script src="{% static 'assets/js/countdown.min.js' %}"></script>
    
    <script src="{% static 'assets/js/ajaxchimp.min.js' %}"></script>
    
    <script src="{% static 'assets/js/form-validator.min.js' %}"></script>
    
    <script src="{% static 'assets/js/contact-form-script.js' %}"></script>
    <script src="{% static 'assets/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script async src="{% static 'assets/js/svg-loader.js' %}"></script>
</body>
</html>